Users:
    type: entity
    table: users
    id:
        idusers:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        username:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        roleId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: role_id
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
    lifecycleCallbacks: {  }
